In [1]:
import numpy as np 


In [2]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
b=np.linspace(10,100,10,dtype=int,endpoint=False,retstep=True)
print(b)

(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), 9.0)


In [4]:
c=np.linspace(0,100,20,endpoint=False,dtype=int,retstep=True)
print(c)

(array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95]), 5.0)


In [5]:
d=np.logspace(1,10,20,base=2,dtype=int)
print(d)

[   2    2    3    5    7   10   14   19   27   38   53   74  102  142
  198  275  382  531  737 1024]


In [8]:
e=np.logspace(1,10,10,dtype=int)
print(e)

[         10         100        1000       10000      100000     1000000
    10000000   100000000  1000000000 -2147483648]


In [9]:
v=np.arange(10,100,10)
v

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
n=np.arange(10,70,10)
n

array([10, 20, 30, 40, 50, 60])

In [14]:
n.reshape([2,3])

array([[10, 20, 30],
       [40, 50, 60]])